### ISSUE TITLE
Examples depend on solph v0.4

### ISSUE THREAD

**Issue by DeepFluxion** [oemof/oemof-thermal#184]
I'm trying to run the code `examples/absorption_heatpump_and_chiller/absorption_chiller.py`, but  when I run the comand `import oemof.thermal.absorption_heatpumps_and_chillers` it appears the following error:

>**_ImportError: cannot import name 'Transformer' from 'oemof.solph' (/usr/local/lib/python3.9/dist-packages/oemof/solph/__init__.py)_**

Could you help me?

Regards

**Comment by p-snft** [comment]
Hi @DeepFluxion, thanks for your feedback. With the latest release of solph, we made its structure more explicit. However, somehow we seem to have overlooked that the imports in the examples here are not updated. So, either use solph v0.4, which is the version the example was created for, or use `solph.components.Transformer` instead of `solph.Transformer`. (Unluckily, I don't have the time to fix this right now. If you do so, I'd appreciate when you commit the fixed version.)

**Comment by DeepFluxion** [comment]
Hi Patrick thank you very much for your feedbak, I will follow your instructions and if everything goes well I will forward the results.

**Comment by pebasantaf** [comment]
Hi! Has this problem been identified? I am having the same issue when trying to use oemof.thermal. But it is not only with the examples. It is generally when trying `import oemof.thermal.absorption_heatpumps_and_chillers` (potentially other elements too, but I am not sure). This makes it not possible to use the heat pump with oemof-solph 0.5.0. I was trying to identify where to modify the import of Transformer but was unable to find it.
Thanks in advance!

**Comment by p-snft** [comment]
I believe everything except the examples should be updated to work with solph 0.5. However, there was no "stable" release of thermal since. Would you test the current development version (e.g. from [oemof.thermal 0.0.6.dev2 at PyPI](https://pypi.org/project/oemof.thermal/0.0.6.dev2/))?

**Comment by pebasantaf** [comment]
Alright. I will test it wit the current development version and come back here to share the outcome. Thanks!

**Comment by p-snft** [comment]
If it works, I will make a release of that version.

**Comment by pebasantaf** [comment]
I have installed the last dev version and could import the thermal components and make use of them successfully. So I'd say this specific issue seems to be solved with the 0.06.dev2 version.
